// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/16c0f2c75a30cace4d673b363bbe7af2fe31cc86/source-map-support/source-map-support.d.ts
declare module 'source-map-support' {
	export function install(): any;
}
