// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/a9d2023e8eb1afe534b55758f2f1d16fb69ce61f/form-data/form-data.d.ts
declare module "form-data" {
	export class FormData {
		append(key: string, value: any): FormData;
		getHeaders(): Object;
		// TODO expand pipe
		pipe(to: any): any;
	}
}
