// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/83663818b8176edfe1343e6d7eff688fb1375949/deep-freeze/deep-freeze.d.ts
declare module 'deep-freeze' {
	function df<T>(obj: T): T;
	export = df;
}
