// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/16c0f2c75a30cace4d673b363bbe7af2fe31cc86/exit/exit.d.ts
declare module 'exit' {
	function exit(code: number): void;
	export = exit;
}
