// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/16c0f2c75a30cace4d673b363bbe7af2fe31cc86/open/open.d.ts
declare module 'open' {
	function open(target: string, app?: string): void;
	export = open;
}
