// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/16c0f2c75a30cace4d673b363bbe7af2fe31cc86/detect-indent/detect-indent.d.ts
declare module 'detect-indent' {
	function DetectIndent (dir: string, alt?: string): string;
	export = DetectIndent;
}
