// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/16c0f2c75a30cace4d673b363bbe7af2fe31cc86/jsesc/jsesc.d.ts
declare module 'jsesc' {

	function jsesc(str: string, opts?: any): string;

	module jsesc {
		var version: string;

		interface Opts {
			quotes?: string;
			wrap?: boolean;
			es6?: boolean;
			escapeEverything?: boolean;
			compact?: boolean;
			indent?: string;
			json?: boolean;
		}
	}

	export = jsesc;
}
