// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/47ebd394626861a9d492a7eac1f6aca96df6dfc1/type-detect/type-detect.d.ts
declare module 'type-detect' {
	function type(val: any): string;

	module type {
		export class Library {
			of(val: any): string;
			define (type: string, test: RegExp): void;
			define (type: string, test: (val: any) => boolean): void;
			test (val: any, type: string): boolean;
		}
	}
	export = type;
}
