// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4c09ca98bb22e3fa6964d8d27b9a359e54f9d83c/rimraf/rimraf.d.ts
declare module "rimraf" {
	function rimraf(path: string, callback: (error: Error) => void): void;
	module rimraf {
		export function sync(path: string): void;
		export var EMFILE_MAX: number;
		export var BUSYTRIES_MAX: number;
	}
	export = rimraf;
}
